### ISSUE TITLE
Error on "close" event 

### ISSUE THREAD

**Issue by hemantjp** [reactphp/http-client#120] opened 2018-01-17 16:16 UTC
i wanted to reject the promise based on timer to cancel the request.
Kindly advise

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to {closure}() must be an instance of Exception, none given, called in /vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php on line 123 `

```
public function call()
    {
        $this->request = $this->client->request($this->method, $this->url);
        $deferred = new Deferred();
        $this->request->on('response', function (\React\HttpClient\Response $response)use ($deferred) {
            $response->on('data', function ($chunk) use ($deferred){
                    $deferred->resolve($chunk);
            });
        });
        $this->request->on('error', function (\Exception $e) use ($deferred){
            $deferred->reject($e->getMessage());
        });

Error thrown here
        // $this->request->on('close', function (\Exception $e) use ($deferred){
        //    $deferred->reject($e$e->getMessage());
        // });
        
        $this->request->end();
        return $deferred->promise();
    }

    public function close(){
        $this->request->close();
    }
```

```
$mainLoop->addTimer(15.0, function () use ($requestEndpoints) {
        $requestEndpoints->close();
    });
```

**Comment by clue** [comment] 2018-01-17 16:29
HI @hemantjp, I'm not sure I quite follow what your issue is. In case you want to apply a timeout to a pending request, have you seen https://github.com/reactphp/http-client/issues/104#issuecomment-317196193?

If your problem persists, can you give a short gist to reproduce the problem you're seeing and/or provide a more detailed exception trace?

**Comment by hemantjp** [comment] 2018-01-17 17:13
@clue , i have already referred to #104 . The close event of the request is not getting the proper arguments. i have passed it an exception class but it is saying none supplied.
attached is almost the complete stacktrace.

could this be an issue because i am using php7?

Should i provide more details?

**Comment by clue** [comment] 2018-01-17 17:18
> The close event of the request is not getting the proper arguments. i have passed it an exception class but it is saying none supplied.

The `Request` implements `WritableStreamInterface`, so its documentation also applies (https://github.com/reactphp/stream#writablestreaminterface): The `close` event does not receive any arguments! You should probably use the `error` event in this case, which will report an `Exception` as per the above documentation.

I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2018-01-17 17:18 UTC
Labels: help wanted, question

**Comment by hemantjp** [comment] 2018-01-17 17:49
@clue the `error` event does not get triggered when i forcibly close the request.
Any suggestion as to how to trigger the promise reject.
i need to handle it down stream on a forcible timeout event.

**Comment by clue** [comment] 2018-01-17 18:12
> the error event does not get triggered when i forcibly close the request.
Any suggestion as to how to trigger the promise reject.

Yes, explicitly calling `close()` will only emit the `close` event, not the `error` event. This is expected behavior. What promise are you referring to here? This API does not use promises right now (#41).

**Comment by hemantjp** [comment] 2018-01-17 18:34
@clue Referring to the deferred object i have created to maintain promise like feel.
```
public function call()
    {
        $this->request = $this->client->request($this->method, $this->url);
/* this deferred object*/
        $deferred = new Deferred();
        $this->request->on('response', function (\React\HttpClient\Response $response)use ($deferred) {
            $response->on('data', function ($chunk) use ($deferred){
                    $deferred->resolve($chunk);
            });
        });
        $this->request->on('error', function (\Exception $e) use ($deferred){
            $deferred->reject($e->getMessage());
        });

Error thrown here
        // $this->request->on('close', function (\Exception $e) use ($deferred){
        //    $deferred->reject($e->getMessage());
        // });
        
        $this->request->end();
        return $deferred->promise();
    }

    public function close(){
        $this->request->close();
    }
```

**Comment by clue** [comment] 2018-01-17 18:38
Your API seems to suffer from a number of flaws, e.g. it looks like your API is subject to a temporal dependence. If you explicitly call your `close()` method, you could as well access your `Deferred` to explicitly `reject()` it. As an alternative, you may register to the `close` event and just `reject()` with a generic error there.

**Comment by hemantjp** [comment] 2018-01-17 19:49
@clue thank you sir. i was mislead thinking that `close` event needed an argument. it should have dawned on me it didnt need one
