### ISSUE TITLE
Response->on('end') signature weirdness?

### ISSUE THREAD

**Issue by andig** [reactphp/http-client#80] opened 2017-04-04 16:22 UTC
I've got the following simple code which sends a request and displays the response. 

Problem: the echoed buffer will always be `string(0)` unless I declare it as `&buffer` in the `on('end')`. `string(0)` is how the buffer is initialized:

	$request = $client->request(
		'POST',
		$url,
		array(
			'Content-Length' => strlen($data),
			'Content-Type' => 'application/json'
		)
	);

	$request->on('response', function ($response) {
		$buffer = '';

		$response->on('data', function ($data, $response) use (&$buffer) {
			$buffer .= (string) $data;
		});

		$response->on('end', function ($error) use ($response, $buffer /* < by ref matters */) {
			echo(sprintf("HTTP %d\n", $response->getCode()));
			if ($buffer) {
				echo($buffer . PHP_EOL);
			}
		});
	});

	$request->end($data);

Might this be a problem with PHP-internal optimization?

**Comment by clue** [comment] 2017-04-04 16:52
This sounds like a duplicate of #70? :-) This is something I'm currently working on, so stay tuned :+1:

**Comment by clue** [comment] 2017-04-04 16:54
Sorry, misinterpreted your issue.

This is in fact expected behavior, because you would otherwise bind the initial variable value to your closure, but you actually want the value that changes over time (due to your `data` callback).

I hope this helps :+1:

I believe this has been answered, so I'll close this for now. Please feel free to come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2017-04-04 16:54 UTC
Labels: question

**Comment by andig** [comment] 2017-04-04 16:56
> This is in fact expected behavior, because you would otherwise bind the initial variable value to your closure, but you actually want the value that changes over time (due to your data callback).

I was always under the impression that binding by ref is only required for writing back. But your explanation makes much more sense, big thanks for taking the time!
